package com.comviva.interop.txnengine.enums;

public enum ValidationErrors {
    VALID("8001", Sources.INTEROP),

    INVALID_LANGUAGE("50003", Sources.INTEROP), //
    INTEROP_REFERENCE_ID_MISSING("50002", Sources.INTEROP), //
    INCORRECT_AMOUNT_FORMAT("50004", Sources.INTEROP), //
    SENDER_MSISDN_SHOULD_BE_NUMERIC("50005", Sources.INTEROP), //
    SENDER_MSISDN_MISSING("50006", Sources.INTEROP), //
    INVALID_SENDER_MSISDN_LENGTH("50007", Sources.INTEROP), //
    RECEVIER_MSISDN_SHOULD_BE_NUMERIC("50008", Sources.INTEROP), //
    RECEVIER_MSISDN_MISSING("50009", Sources.INTEROP), //
    INVALID_RECEVIER_MSISDN_LENGTH("50010", Sources.INTEROP), //
    EXT_ORG_REF_ID_MISSING("50011", Sources.INTEROP), //
    INVALID_CURRENCY("50012", Sources.INTEROP), //
    TRANSACTION_TYPE_MISSING("50013", Sources.INTEROP), //
    LANGUAGE_MISSING("50014", Sources.INTEROP), //
    INVALID_DATE_FORMAT("50015", Sources.INTEROP), //
    LANGUAGE_NOT_SUPPORTED("50017", Sources.INTEROP), //
    SENDER_PARTY_DETAILS_MISSING("50018", Sources.INTEROP), //
    RECEIVER_PARTY_DETAILS_MISSING("50019", Sources.INTEROP), //
    PIN_MISSING("50020", Sources.INTEROP), //
    INVALID_PIN_LENGTH("50021", Sources.INTEROP), //
    CURRENCY_MISSING("50022", Sources.INTEROP), //
    INVALID_PIN("50023", Sources.INTEROP), //
    NO_RESPONSE_FROM_EIG("50026", Sources.INTEROP), //
    THIRD_PARTY_STATUS_CODE_MISSING("50025", Sources.INTEROP),//
    SENDER_PARTY_PIN_MISSING("50031", Sources.INTEROP),//
    SENDER_PARTY_MSISDN_MISSING("50032", Sources.INTEROP),//
    INVALID_TRANSACTION_TYPE("50033", Sources.INTEROP), //
    INVALID_USER_ENROLLMENT_STATUS("50034", Sources.INTEROP), //
    PROCESSING_CODE_MISSING("50035", Sources.INTEROP),//
    SYSTEMAUDITNUMBER_MISSING("50036", Sources.INTEROP),//
    REFERENCE_NUMBER_MISSING("50037", Sources.INTEROP),//
    COUNTRY_CODE_MISSING("50038", Sources.INTEROP), //
    INVALID_TRANSACTION_ID("50039", Sources.INTEROP), //
    ALREADY_TRANSACTION_CORRECTED("50040", Sources.INTEROP), //
    NO_OF_TXNS_SHOULD_BE_NUMERIC("50041", Sources.INTEROP), //
    ACTION_TYPE_MISSING("50042", Sources.INTEROP), //
    INVALID_ACTION_TYPE("50043", Sources.INTEROP), //
    INVALID_TXN_CORRECTION_REF_ID("50044", Sources.INTEROP), //
    TXN_REJECTED("50045", Sources.INTEROP), //
    REQUEST_RESOURCE_MISSING("50047", Sources.INTEROP), //
    SOURCE_ACCOUNT_TYPE_MISSING("50048", Sources.INTEROP), //
    INVALID_REQUEST_RESOURCE("50049", Sources.INTEROP), //
    INVALID_SOURCE_ACCOUNT_TYPE("50050", Sources.INTEROP), //
    USER_ID_MISSING("50051", Sources.INTEROP), //
    USER_PASSWORD_MISSING("50052", Sources.INTEROP), //
    NETWORK_ACTION_MISSING("50053", Sources.INTEROP), //
    
    ;
    private final String statusCode;
    private final Sources entity;

    private ValidationErrors(String statusCode, Sources entity) {
        this.statusCode = statusCode;
        this.entity = entity;
    }

    public String getStatusCode() {
        return this.statusCode;
    }

    public Sources getEntity() {
        return this.entity;
    }

}