package com.comviva.interop.txnengine.enums;

public enum TestCaseConstants {

	API_KEY_HEADER("Authorization"),
	API_KEY_HEADER_VALUE("247213da688a2558b805db784978ed6fa778f082189f77fc2a0be2925bee5d3e"),
	INTEROP_REFERENCE_ID_NAME("interopRefId"),
	INTEROP_REFERENCE_ID_VALUE("1255255255"),
	LANGUAGE_KEY("\"lang\""),
	LANGUAGE_VALUE("\"fr\""),
	DEFAULT_LANGUAGE_CODE("\"fr\""),
	LEFT_CURLY_BRACE("{"),
	RIGHT_CURLY_BRACE("}"),
	LEFT_ARRAY("["),
	RIGHT_ARRAY("]"),
	COLON(":"),
	COMMA(","),
	MSISDN_KEY("\"msisdn\""),
	REQUEST_SOURCE_KEY("\"requestSource\""),
	REQUEST_SOURCE_VALUE("\"USSD\""),
	EXTORG_REF_ID_KEY("\"extOrgRefId\""),
	EXTORG_REF_ID_VALUE("\"12345566778\""),
	INVALID_LENGTH_MSISDN("\"1234567\""),
	INVALID_MSISDN("\"234789rfw44\""),
	EMPTY("\"\""),
	INVALID_LANGUAGE_VALUE("\"english\""),
	LANGUAGE_CODE("en"),
	DEFAULT_MSISDN("\"1234567890\""),
	MAPPED_CODE_NAME("mappedCode"),
	CODE_NAME("code"),
	AMOUNT_KEY("\"amount\""),
	TRANSACTIONS_BASE_CONTEXT("/v1/transactions/"),
	DEFAULT_AMOUNT("\"10\""),
	CREDIT_PARTY_KEY("\"creditParty\""),
	KEY_NAME("\"key\""),
	VALUE_NAME("\"value\""),
	CURRENCY_NAME("\"currency\""),
	DEFAULT_CURRENCY("\"INR\""),
	DEBIT_PARTY_KEY("\"debitParty\""),
	PIN_NAME("\"pin\""),
	DEFAULT_PIN("\"1234\""),
	INVALID_PIN("\"123456\""),
	NON_NUMERIC_PIN("\"FFDD\""),
	EXT_ORG_REF_ID_NAME("\"extOrgRefId\""),
	EXT_ORG_REF_ID_VALUE("\"555555\""),
	DEFAULT_EXT_ORG_REF_ID_VALUE("555555"),
	TXN_TYPE_NAME("\"transactionType\""),
	P2P_TXN_TYPE_VALUE("\"p2p\""),
	DEFAULT_PAYER_MSISDN("\"1234567890\""),
	DEFAULT_PAYEE_MSISDN("\"1234567891\""),
	BASE_CONTEXT("/v1/users/"),
	BASE_CONTEXT_END("/activation"),
	OTP_KEY("\"otp\""),
	OTP_VALUE("\"12345\""),
	INVALID_AMOUNT_VALUE("\"12ef\""),
	INVALID_CURRENCY("\"INRR\""),
	DEFAULT_WALLET_STATUE("defaultWalletStatus"),
	ENROLMENT_REG_SUCCESS_STATUS("00"),
	NOT_REGISTERED_WITH_HPS("00"),
	MAPPED_CODE_VALUE("00000"),
	CODE("code"),
	CODE_VALUE_SUCCESS("INTEROP_40078"),
	CODE_VALUE_FAILURE("INTEROP_40077"),
	ERRORDEFAULT_INTERNAL("ERRORDEFAULT_INTERNAL"),
	INTEROP_50001("INTEROP_50001"),
	INVALIDREQUEST_INVALID_AMOUNT("INVALIDREQUEST_INVALID_AMOUNT"),
	INVALIDREQUEST_INVALID_TRANSACTION_TYPE("INVALIDREQUEST_INVALID_TRANSACTION_TYPE"),
	INVALIDREQUEST_MISSING_MSISDN("INVALIDREQUEST_MISSING_MSISDN"),
	INVALIDREQUEST_MISSING_EXTERNAL_ORGANISATION_REFERENCE_ID("INVALIDREQUEST_MISSING_EXTERNAL_ORGANISATION_REFERENCE_ID"),
	INVALIDREQUEST_MISSING_CURRENCY("INVALIDREQUEST_MISSING_CURRENCY"),
	BROKER_FAILURE("BROKER_FAILURE"),
	TRANSACTION_QUOTATION_URL("/v1/transactions/quotation"),
	RECEIVE_TRANSACTION_URL("/v1/receivetransactions/"),
	CHANNEL_USER_CODE("12365"),
	COUNTRY_ID("25"),
	COUNTRY_ID_VALUE("MA"),
	CHANNEL_USER("CHANNEL_USER"),
	OPTIONAL_MSG("OPTIONAL"),
	CHANNEL_USER_ID("8888"),
	LANGUAGE_PARAM("lang="),
	BROKER_SUCCESS_STATUS_CODE("BROKER_200"),
	DEFAULT_AMOUNT_VALUE("10"),
	FROM_PARAM("from="),
	LIMIT_PARAM("limit="),
	DEFAULT_COUNTRY_ID("MA"),
	INTER_OP_TXN_ENGIN_NAME("interopTxn"),
	SMS_ID("smsId"),
	TXN_ID_VALUE("CO190311.1133.R00023"),
	TXN_CORRECTION_APPROVE_URL_VALUE("http://172.30.70.150:8000/wallet/txncorrectionapprove/addon_id/UT/country_id/sn/currency/INR"),
	TXN_CORRECTION_INIT_URL_VALUE("http://172.30.70.150:8000/wallet/txncorrectioninit/addon_id/UT/country_id/sn/currency/INR"),
	USER_AUTH_URL_VALUE("http://172.30.70.150:8000/wallet/delegatedauth/addon_id/UT/country_id/sn/currency/INR"),
	CASH_OUT_INIT_URL_VALUE("http://172.30.70.150:8000/wallet/delegatedauth/addon_id/UT/country_id/sn/currency/INR"),
	CASH_OUT_CONFIRM_URL_VALUE("http://172.30.70.150:8000/wallet/cashoutconfirm/addon_id/UT/country_id/sn/currency/INR"),
	P2POFF_US_VALUE("P2P Off Us"),
	ZERO("0"),
	ONE("1"),
	REMARKS("transaction correction"),
	ACTION("TI"),
	SCREVERSAL("screversal"),
	CHANNEL_USER_MSISDN("1010101010"),
	TXN_MODE_VAL_P2PON("01#P2PONUS#TRN####1558095160##1#"),
	TXN_MODE_VAL_P2POFF("01#P2POFFUS#TRN####1558095160##1#"),
    
 // receiveTransaction
    PAN("0674909149"),//
    PROCESSING_CODE("230000"),//
    TRANSACTION_AMOUNT("000000010000"),//
    DATEANDTIME_TRANSMISSION("1807121734"),//
    CARDHOLDERBILLINGEEXCHANGERATE("61000000"),//
    SYSTEMAUDITNUMBER("754000"),//
    DATEANDTIMEOFTHETRANSACTION("180712173435"),//
    SETTLEMENTDATE("190118"),//
    EXCHANGEDATE("0712"),//
    BUSINESSTYPE("0600"),//
    COUNTRY_CODE("504"),//
    SERVICEPOINTDATACODE("510301X11146"),//
    FUNCTIONCODE("200"),//
    IDENTIFICATIONCODEOFTHEACQUIRINGORGANIZATION("000011"),//
    IDENTIFICATIONCODEOFTHESENDINGORGANIZATION("808080"),//
    REFERENCENUMBEROFTHERECOVERY("819317754000"),//
    CURRENCYCODE("INR"),//
    SOURCEACCOUNTNUMBER("0666953548"),//
    DESTINATIONACCOUNTNUMBER("0674909149"),//
    PROCESSING_CODE_MISSING("PROCESSING_CODE_MISSING"),//
    REFERENCE_NUMBER_MISSING("REFERENCE_NUMBER_MISSING"),//
    SYSTEMAUDITNUMBER_MISSING("SYSTEMAUDITNUMBER_MISSING"),//
    COUNTRY_CODE_MISSING("COUNTRY_CODE_MISSING"),//
    ACTION_CODE_NAME("actionCode"), //
    MP_TXN_TYPE_VALUE("\"merchantPayment\""), //
    TRANSACTION_CORRECTION_CONTEXT("/v1/transactions/txn_correction"), //
    EXT_ORG_REF_ID("extOrgRefId"), //
    PENDING_TRANSACTIONS_BASE_CONTEXT("/v1/transactions/pending/"), //
    MP_PULL_TXN_TYPE_VALUE("\"merchantPaymentPull\""), //
    CONFIRM_TRANSACTIONS_BASE_CONTEXT("/v1/transactions/action"), //
    PIN("1234"),
    DEBITPARTY_CREDENTIALS_KEY("\"debitPartyCredentials\""),
	EM("\"em\""),
	SOURCE_ACCOUNT_TYPE_KEY("\"sourceAccountType\""),
	NETWORK_MESSAGE_URL("/v1/edp/networkMessage"), //
	;
	
	private String value;
	
	private TestCaseConstants(String value) {
		this.value = value;
	}
	
	public String getValue() {
		return this.value;
	}
}
